apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "restarter.fullname" . }}
  labels:
    {{- include "restarter.labels" . | nindent 4 }}
rules:
  - verbs:
      - get
      - patch
      - list
      - watch
    apiGroups:
      - apps
      - extensions
    resources:
      - deployments
      - deployments/scale
      - daemonsets      
    resourceNames:
    {{- range .Values.restart }}
     {{- range .deployments }}
    - {{ . }}
     {{- end }}
    {{- end }}
    {{- range .Values.restart }}
     {{- range .daemonsets }}
    - {{ . }}
     {{- end }}
    {{- end }}    
    {{- range .Values.scaleDownUp }}
     {{- range .deployments }}
    - {{ .name }}
     {{- end }}
    {{- end }}

